package wasmtime:test;

world types {
    include wasi:foo/imports@0.2.3;
    include wasi:unstable/imports@0.2.3; 
} 

package wasi:unstable@0.2.3 {
    @unstable(feature = active)
    world imports {
        @unstable(feature = active)
        use wasi:dep2/stable@0.2.3.{stable-resource};
    }
}

package wasi:foo@0.2.3 {
    @since(version = 0.2.0)
    world imports {
        @since(version = 0.2.0)
        include wasi:dep2/imports@0.2.3;
    }
}

package wasi:dep2@0.2.3 {
    @since(version = 0.2.0)
    world imports {
        @since(version = 0.2.0)
        import stable;
    }
    @since(version = 0.2.0)
    interface stable {
        resource stable-resource {
        }
    }
}

